### ISSUE TITLE
[BUG] 查看低分辨率图片时崩溃

### ISSUE THREAD

**Issue by duzhaokun123** [duzhaokun123/BilibiliHD#16]
### bug 表现
查看低分辨率图片时崩溃

### 重现步骤
随便找个低分辨率图片查看

### 预期行为
正常查看

### 屏幕截图
null

### Log
```
02-06 00:49:09.570  8996  8996 E AndroidRuntime: FATAL EXCEPTION: main
02-06 00:49:09.570  8996  8996 E AndroidRuntime: Process: com.duzhaokun123.bilibilihd, PID: 8996
02-06 00:49:09.570  8996  8996 E AndroidRuntime: java.lang.IllegalArgumentException: Minimum zoom has to be less than Medium zoom. Call setMinimumZoom() with a more appropriate value
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at com.github.chrisbanes.photoview.Util.checkZoomLevels(Util.java:11)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at com.github.chrisbanes.photoview.PhotoViewAttacher.setMinimumScale(PhotoViewAttacher.java:385)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at com.github.chrisbanes.photoview.PhotoView.setMinimumScale(PhotoView.java:194)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at com.duzhaokun123.bilibilihd.utils.ImageViewUtil$viewImage$2$1$onResourceReady$1$1.invokeSuspend(ImageViewUtil.kt:148)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
02-06 00:49:09.570  8996  8996 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

### 系统及应用信息
 - 设备: any (屏幕越大越可能发生)
 - 系统: any
 - 应用版本: 0.1.4+af67f71, 0.1.4+ac2927e
 - 应用构建类型: any

**Comment by duzhaokun123** [comment]
`PhotoView`的问题，一定要先算好Scale再设置

**Comment by duzhaokun123** [comment]
fixed
